### ISSUE TITLE
代码文档化建议

### ISSUE THREAD

**Issue by Mainvooid** [linyouhappy/mushroom#1]
这个项目挺不错的，我有几个不成熟的建议

- 代码文档化
   - 数据结构体有些意义不够明显的成员建议注释
   - 文档化有利于快速上手，以及代码阅读
   - 文档化工具推荐Doxygen

- 对项目进行分层，如果KCP换成其他协议能否进行良好的插拔
   - KCP层
   - Socket层
   - TCP,UDP层

- 不应该限定KCP的下层传输协议
   - 虽然大部分时候是增强UDP
   - 解决这类问题有利于项目扩展性与健壮性

- kcp需要保证通信双方会话标识相同，所以需要在kcp连接建立前进行一个同步，能否支持?

**Comment by linyouhappy** [comment]
因为生计问题，一直没空去维护处理，甚至把这个项目丢弃掉。没办法啊，要吃饭啊。没找到好去处。如果能给我一两万的生活费，一定会优化好，各个平台进行实现。以及加demo。

**Comment by linyouhappy** [comment]
> 这个项目挺不错的，我有几个不成熟的建议
> 
> * 代码文档化
>   
>   * 数据结构体有些意义不够明显的成员建议注释
>   * 文档化有利于快速上手，以及代码阅读
>   * 文档化工具推荐Doxygen
> * 对项目进行分层，如果KCP换成其他协议能否进行良好的插拔
>   
>   * KCP层
>   * Socket层
>   * TCP,UDP层
> * 不应该限定KCP的下层传输协议
>   
>   * 虽然大部分时候是增强UDP
>   * 解决这类问题有利于项目扩展性与健壮性
> * kcp需要保证通信双方会话标识相同，所以需要在kcp连接建立前进行一个同步，能否支持?

找工作一个多月了，还在为找工作犯愁。

**Comment by Mainvooid** [comment]
emmm...我暂时也帮不了你，以你对网络协议的熟悉，如果在北上广找工作应该挺容易的吧，加油！
这个项目的目标挺好的，涉及KCP还是值得维护的，但是总体架构设计还有优化空间，闲暇时间如果能顺手维护好，未来总是有机会的。5G，云游戏，物联网，大量的低延迟应用场景，对高性能低延迟网络通信框架的需求会增加。
